package main

const ENV_API_URL = "MATTR_API_URL"
const ENV_AUTH_URL = "MATTR_AUTH_URL"
const ENV_AUTH_AUDIENCE = "MATTR_AUDIENCE"
const ENV_CLIENT_ID = "MATTR_CLIENT_ID"
const ENV_CLIENT_SECRET = "MATTR_CLIENT_SECRET"
