# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Integration test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: Build locally
      run: ./build.sh

    - name: Deploy locally
      run: ./deploy.sh

    - name: Run test
      run: |
        cd test/
        ./run-tests.sh
