name: Generate changelog

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Changelog
        uses: TriPSs/conventional-changelog-action@v5.4.0
        with:
          fallback-version: v0.1.3
          git-push: true
          skip-version-file: true
          skip-ci: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
